To: laplansk@gmail.com
From: lineup.bugs@gmail.com
Subject: LineUp AutoTester


Traceback (most recent call last):
  File "flask_tests/test.py", line 5, in <module>
    from app import app
ImportError: No module named app
